# Generated by Django 4.2 on 2023-05-02 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee_user_id',
            field=models.ManyToManyField(blank=True, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
