# Generated by Django 4.2 on 2023-05-04 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0002_alter_issue_assignee_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee_user_id',
            field=models.ManyToManyField(related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
